mongo:
  image: mongo
  command: ['mongod', '--smallfiles']
app:
  image: codechaotic/node
  working_dir: /app
  command: app.js
  restart: on-failure:5
  ports:
    - 127.0.0.1:80:8080
  volumes:
    - dist/:/app
  links:
    - mongo
